### ISSUE TITLE
Possible to connect both halves with an ethernet crossover cable

### ISSUE THREAD

**Issue by fuzzbomb** [keyboardio/Kaleidoscope-Hardware-Model01#20]
While experimenting with patch cables of different lengths, I found one that did't work.  Turns out it was a crossover type of cable.

I guess the board halves probably talk using using I2C over Cat5 rather than Ethernet, but is it possible for the firmware to figure out that a crossover cable is being used?  Bit of an edge case improvement,just thought I'd note it.

**Comment by obra** [comment]
The pinout of the connectors is

1 - DSCL_M
2 - DSCL_P
3 - DSDA_M
4 - +5V
5 - +5V
6 - DSDA_P
7 - GND
8 - GND

This is all hard-wired. I don't believe there's any rational way we could
support both,  even with a hardware change

**Comment by fuzzbomb** [comment]
Fair enough, just wondered whether it was possible, because folk will have old cables lying around.  We could close this as a firmware feature request in that case.

On the other hand, this also counts as something worth documenting in a user guide, say.  "Crossover cables not supported."

There were no ill effects from using a crossover cable AFAIK.  I connected the crossover cable first, then the USB cable to the computer.  The left side briefly flashed some LEDs (a booting sequence, maybe?), but no keys responded.  With a different patch cable, all was good again.

Incidentally, this discovery was motivated by finding a cable *just* long enough that I could fit a big fat kensington  trackball between the two halves.  The Goldilocks length.

**Comment by fuzzbomb** [comment]
I guess this could live in a "troubleshooting FAQ" or similar
